### ISSUE TITLE
When dragging and dropping non-rep file on the D-Lite, it silently fails

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3697]
When dragging and dropping non-rep file on the D-Lite, it fails silently, no proper warning dialog is shown . Sometimes it  shows this error dialog 
[![Image from Gyazo](https://i.gyazo.com/9fec1152e326d662d88cb500787f0f47.png)](https://gyazo.com/9fec1152e326d662d88cb500787f0f47) and logs  this 
[DynamicLayer handler not found.txt](https://github.com/debrief/debrief/files/2832784/DynamicLayer.handler.not.found.txt)

### Expected Result
It should show warning Message ,that informs the user that he/she should drag-drop only rep files.

**Comment by helenayele** [comment]
And also D-Lite should support Both xml and dpf file types in addition to rep files.

**Comment by IanMayo** [comment]
@helenayele - could you re-validate this, please?

**Comment by helenayele** [comment]
Okay, now , when I try to load some problematic dpf files like sample.dpf, boat1t.dpf files, it silently logs the below exception and D-Lite becomes busy for long period of time. I can only terminate it from eclipse.
java.lang.IllegalArgumentException: not implemented (yet)
	at org.mwc.debrief.lite.LiteParent.logError(LiteParent.java:13)
	at MWC.Utilities.Errors.Trace.trace(Trace.java:222)
	at MWC.Utilities.Errors.Trace.trace(Trace.java:155)
	at org.mwc.debrief.lite.DebriefLiteApp.FilesReceived(DebriefLiteApp.java:527)
	at MWC.GUI.DragDrop.FileDropSupport.fileReceived(FileDropSupport.java:145)
	at MWC.GUI.DragDrop.FileDropSupport.drop(FileDropSupport.java:179)
	at java.awt.dnd.DropTarget.drop(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(Unknown Source)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by saulhidalgoaular** [comment]
> Okay, now , when I try to load some problematic dpf files like sample.dpf, boat1t.dpf files, it silently logs the below exception and D-Lite becomes busy for long period of time. I can only terminate it from eclipse.
> java.lang.IllegalArgumentException: not implemented (yet)
> at org.mwc.debrief.lite.LiteParent.logError(LiteParent.java:13)
> at MWC.Utilities.Errors.Trace.trace(Trace.java:222)
> at MWC.Utilities.Errors.Trace.trace(Trace.java:155)
> at org.mwc.debrief.lite.DebriefLiteApp.FilesReceived(DebriefLiteApp.java:527)
> at MWC.GUI.DragDrop.FileDropSupport.fileReceived(FileDropSupport.java:145)
> at MWC.GUI.DragDrop.FileDropSupport.drop(FileDropSupport.java:179)
> at java.awt.dnd.DropTarget.drop(Unknown Source)
> at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(Unknown Source)
> at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(Unknown Source)
> at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(Unknown Source)
> at sun.awt.dnd.SunDropTargetEvent.dispatch(Unknown Source)
> at java.awt.Component.dispatchEventImpl(Unknown Source)
> at java.awt.Container.dispatchEventImpl(Unknown Source)
> at java.awt.Component.dispatchEvent(Unknown Source)
> at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
> at java.awt.LightweightDispatcher.processDropTargetEvent(Unknown Source)
> at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
> at java.awt.Container.dispatchEventImpl(Unknown Source)
> at java.awt.Window.dispatchEventImpl(Unknown Source)
> at java.awt.Component.dispatchEvent(Unknown Source)
> at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> at java.awt.EventQueue.access$500(Unknown Source)
> at java.awt.EventQueue$3.run(Unknown Source)
> at java.awt.EventQueue$3.run(Unknown Source)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> at java.awt.EventQueue$4.run(Unknown Source)
> at java.awt.EventQueue$4.run(Unknown Source)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> at java.awt.EventQueue.dispatchEvent(Unknown Source)
> at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> at java.awt.EventDispatchThread.run(Unknown Source)

Good morning @helenayele 

I have added some error messages when it tries to open invalid dpf files. It would be good if you attach your invalid file.

Thanks.
Saul.

**Comment by helenayele** [comment]
Now when I try to open invalid files like boat1t.dpf file, I get this dialog opened
[![Image from Gyazo](https://i.gyazo.com/8ec9f16a321067184cd9a779fd68ac46.png)](https://gyazo.com/8ec9f16a321067184cd9a779fd68ac46)

some list of invalid files are :
From  SATC folder

- MDA_Test.dpf 
- old_turn_example.dpf 
- thirty_min_earlier_first_turn.dpf ,thirty_min_extra_leg.dpf ,thiry_min_one.dpf

2. When I try to drag sensor data(sen_ssk_sensor) on dpf files, I get this - [![Image from Gyazo](https://i.gyazo.com/ba89e23be193661f0ae9527995983751.png)](https://gyazo.com/ba89e23be193661f0ae9527995983751)

**Comment by IanMayo** [comment]
@helenayele - I think those error messages are ok.

The first dialog will get fixed in #3683 

I'm not sure about the second one. Let me investigate.

**Comment by saulhidalgoaular** [comment]
Hi @helenayele Title changed

**Comment by helenayele** [comment]
I still get this dialog when I load invalid file - For example I load this xml file:
[NewFile.zip](https://github.com/debrief/debrief/files/3067643/NewFile.zip)
And I get the below dialog:
[![Image from Gyazo](https://i.gyazo.com/7bd821eb36842bce9e36a5506c06d398.png)](https://gyazo.com/7bd821eb36842bce9e36a5506c06d398)

The title and the message are not per our previous conversation please ?

**Comment by IanMayo** [comment]
that's a bit sneaky @helenayele  😉 

The other example was for a valid XML file that wasn't in Debrief format.  This is a Frankenstein file 🤣 

I'm ok with this error, to be honest.  It's directing the analyst to the point where the file seems broken.  I _don't think_ we need to write any more.

**Comment by helenayele** [comment]
@IanMayo  it is okay for the message but my expectation was to get the proper title for dialog

**Comment by IanMayo** [comment]
Oh, ok.

I don't remember that conversation. What would you like the title to be?

**Comment by helenayele** [comment]
we discussed in west channel ,and I suggest it to be "Error in opening file"

**Comment by IanMayo** [comment]
Aah, ok.

**Comment by helenayele** [comment]
Currently we show 2 different error dialog titles for invalid rep and dpf files , can we make them uniform please - https://github.com/debrief/debrief/pull/4022#pullrequestreview-226061113

**Comment by IanMayo** [comment]
Done.

**Comment by helenayele** [comment]
Now D-Lite shows error dialog with uniform title while opening invalid REP and DPF files as well as XML files. 

[![Image from Gyazo](https://i.gyazo.com/67780043caddc1446273e841e30dfb6b.png)](https://gyazo.com/67780043caddc1446273e841e30dfb6b)
So verifying..
