### ISSUE TITLE
Extended Symbology in Rep files affects the Track style.

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4932]
The file attached should load the regular `boat1.rep`. However, track style is getting affected.
[boat1.zip](https://github.com/debrief/debrief/files/4975664/boat1.zip)

**Comment by IanMayo** [comment]
@saulhidalgoaular - could you give me a better understanding of what the issue is here, please?

**Comment by saulhidalgoaular** [comment]
Good afternoon.

When I have implemented the extended symbology for `rep` files to include the NEW_SEGMENT, I realized that the parser was reading part of the extended symbology as the regular symbology. It means that the '[' and the 'N' were interpreted as the 3rd and 4rd character.

With this PR I am forcing to read only the characters before the '['

**Comment by saulhidalgoaular** [comment]
Currently in `develop` when the '[' and 'N' are interpreted as part of the regular symbology, we get the following tracks.
https://gyazo.com/06ee102b8a642ac67eb3c5c1e217d582
https://gyazo.com/2da84aa68dc6527b773a7c4efaa7a531

**Comment by helenayele** [comment]
I still see these
[![Image from Gyazo](https://i.gyazo.com/efef4a095cdde7a4d8f8e160eab75f5e.png)](https://gyazo.com/efef4a095cdde7a4d8f8e160eab75f5e)

[![Image from Gyazo](https://i.gyazo.com/c160f999a8890f2f6c16aa4e51f83b74.png)](https://gyazo.com/c160f999a8890f2f6c16aa4e51f83b74)
in develop branch.

**Comment by saulhidalgoaular** [comment]
Good morning @helenayele 

I cannot reproduce it. Are you sure you are in `develop` in a commit after this branch was merged?

**Comment by helenayele** [comment]
I tried with the above attached boat1.zip file and can't reproduce the issue. 
But I am still reproducing with this file 
[boat1_Sample.zip](https://github.com/debrief/debrief/files/5021707/boat1_Sample.zip)
@saulhidalgoaular  can you identify why it is not working for this file please?

**Comment by saulhidalgoaular** [comment]
Good afternoon @helenayele 

It is because in this `rep` file we are indicating that we want a thickness of hairwidth.

![image](https://user-images.githubusercontent.com/11049943/89304975-5b9d3f00-d66e-11ea-8c64-2c5e2af317d5.png)

![image](https://user-images.githubusercontent.com/11049943/89305304-c64e7a80-d66e-11ea-8fe0-cdeaa167d2df.png)

However, when we change the thickness to 5 pixels, it is correctly read.

![image](https://user-images.githubusercontent.com/11049943/89305432-eaaa5700-d66e-11ea-8a90-1b6e8b7c544d.png)

Despite having the new notation.

![image](https://user-images.githubusercontent.com/11049943/89305587-1fb6a980-d66f-11ea-8cd5-a0bca884af8b.png)

**Comment by saulhidalgoaular** [comment]
However, the bug was about showing thickness of a hairwidth for non-specified thickness files (when using the [NEW_SEGMENT])

**Comment by helenayele** [comment]
Yes Saul, clear, thanks.

Now it is working as expected. Closing...
